SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
-- UPDATE THE BELOW TO REFLECT THE NAME OF YOUR MSSQL INSTANCE
Use d42132a56a2994213ba479990595fbac7
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
		   WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Sample' AND TABLE_TYPE = 'BASE TABLE')
BEGIN
	CREATE TABLE dbo.Sample (
	    ID int IDENTITY (1,1) NOT NULL,				
		Text nvarchar(256) NULL,
		CONSTRAINT PK_Sample_ID PRIMARY KEY CLUSTERED (ID)
		)		
END
GO
